runtime: python27
api_version: 1
threadsafe: yes

handlers:
  # static directory for javasript functions
- url: /js
  static_dir: js

- url: /css
  static_dir: css

# static directory for images
- url: /img
  static_dir: img

# accept all calls and route them inside main python file
- url: /.*
  script: views.app

# we use jinja2 templates to generate UI
libraries:
- name: jinja2
  version: latest
